# Generated by Django 4.2.16 on 2026-04-05 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True)),
                ('notification_type', models.CharField(choices=[('document_approved', 'Document Approved'), ('document_rejected', 'Document Rejected'), ('document_flagged', 'Document Flagged'), ('test_published', 'Test Published'), ('test_results_released', 'Test Results Released'), ('test_reminder', 'Test Reminder'), ('auto_submitted', 'Test Auto-Submitted'), ('bulk_import_complete', 'Bulk Import Complete'), ('bulk_import_failed', 'Bulk Import Failed'), ('announcement', 'Announcement'), ('info', 'Info'), ('warning', 'Warning')], default='info', max_length=50)),
                ('action_url', models.CharField(blank=True, max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='users.institution')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_notifications', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', '-created_at'], name='notificatio_recipie_2d3764_idx'), models.Index(fields=['institution', '-created_at'], name='notificatio_institu_e5a241_idx')],
            },
        ),
    ]
