# Generated by Django 4.2.16 on 2026-04-08 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkimportjob',
            name='last_processed_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
