# Generated by Django 4.2.16 on 2026-04-05 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('option_text', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('order_index', models.IntegerField()),
            ],
            options={
                'db_table': 'question_options',
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('active', 'Active'), ('closed', 'Closed'), ('results_released', 'Results Released')], default='draft', max_length=20)),
                ('availability_start', models.DateTimeField()),
                ('availability_end', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField()),
                ('total_marks', models.IntegerField(default=0)),
                ('passing_marks', models.IntegerField(blank=True, null=True)),
                ('shuffle_questions', models.BooleanField(default=False)),
                ('shuffle_options', models.BooleanField(default=False)),
                ('show_answers_after', models.BooleanField(default=False)),
                ('tab_switch_threshold', models.IntegerField(default=3)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tests', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='users.section')),
            ],
            options={
                'db_table': 'tests',
            },
        ),
        migrations.CreateModel(
            name='TestQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('mcq', 'Multiple Choice'), ('short_answer', 'Short Answer'), ('true_false', 'True/False')], max_length=20)),
                ('marks', models.IntegerField(default=1)),
                ('order_index', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assessments.test')),
            ],
            options={
                'db_table': 'test_questions',
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='TestAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('auto_submitted', 'Auto Submitted')], default='not_started', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('time_taken_seconds', models.IntegerField(blank=True, null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('is_passed', models.BooleanField(blank=True, null=True)),
                ('tab_switch_count', models.IntegerField(default=0)),
                ('fullscreen_exit_count', models.IntegerField(default=0)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10)),
                ('teacher_note', models.TextField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_attempts', to=settings.AUTH_USER_MODEL)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='assessments.test')),
            ],
            options={
                'db_table': 'test_attempts',
            },
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text_answer', models.TextField(blank=True, null=True)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('marks_awarded', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('is_marked_review', models.BooleanField(default=False)),
                ('answered_at', models.DateTimeField(auto_now=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='assessments.testattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.testquestion')),
                ('selected_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assessments.questionoption')),
            ],
            options={
                'db_table': 'student_answers',
            },
        ),
        migrations.AddField(
            model_name='questionoption',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='assessments.testquestion'),
        ),
        migrations.CreateModel(
            name='BehavioralEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('tab_switch', 'Tab Switch'), ('fullscreen_exit', 'Fullscreen Exit'), ('fullscreen_enter', 'Fullscreen Enter'), ('test_started', 'Test Started'), ('test_submitted', 'Test Submitted'), ('answer_changed', 'Answer Changed'), ('focus_lost', 'Focus Lost'), ('focus_gained', 'Focus Gained'), ('right_click_attempt', 'Right Click Attempt'), ('keyboard_shortcut_blocked', 'Keyboard Shortcut Blocked')], max_length=50)),
                ('event_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavioral_events', to='assessments.testattempt')),
            ],
            options={
                'db_table': 'behavioral_events',
            },
        ),
        migrations.AddIndex(
            model_name='testquestion',
            index=models.Index(fields=['test'], name='test_questi_test_id_b6d40e_idx'),
        ),
        migrations.AddIndex(
            model_name='testattempt',
            index=models.Index(fields=['test'], name='test_attemp_test_id_ec3b71_idx'),
        ),
        migrations.AddIndex(
            model_name='testattempt',
            index=models.Index(fields=['student'], name='test_attemp_student_bd7726_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='testattempt',
            unique_together={('test', 'student')},
        ),
        migrations.AddIndex(
            model_name='test',
            index=models.Index(fields=['section'], name='tests_section_4a632d_idx'),
        ),
        migrations.AddIndex(
            model_name='test',
            index=models.Index(fields=['status'], name='tests_status_7b792f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentanswer',
            unique_together={('attempt', 'question')},
        ),
        migrations.AddIndex(
            model_name='behavioralevent',
            index=models.Index(fields=['attempt'], name='behavioral__attempt_30b6e6_idx'),
        ),
    ]
