# Generated by Django 4.2.16 on 2026-04-14 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='behavioralevent',
            name='event_type',
            field=models.CharField(choices=[('tab_switch', 'Tab Switch'), ('fullscreen_exit', 'Fullscreen Exit'), ('fullscreen_enter', 'Fullscreen Enter'), ('test_started', 'Test Started'), ('test_submitted', 'Test Submitted'), ('answer_changed', 'Answer Changed'), ('focus_lost', 'Focus Lost'), ('focus_gained', 'Focus Gained'), ('right_click_attempt', 'Right Click Attempt'), ('keyboard_shortcut_blocked', 'Keyboard Shortcut Blocked'), ('copy_attempt', 'Copy Attempt'), ('print_attempt', 'Print Attempt')], max_length=50),
        ),
        migrations.AlterField(
            model_name='testquestion',
            name='question_text',
            field=models.TextField(blank=True),
        ),
    ]
