# Generated by Django 4.2.16 on 2026-04-05 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('document_type', models.CharField(choices=[('notes', 'Notes'), ('assignment', 'Assignment'), ('project', 'Project Report'), ('lab', 'Lab Documentation'), ('presentation', 'Presentation'), ('study_guide', 'Study Guide'), ('other', 'Other')], default='notes', max_length=30)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('tags', models.JSONField(default=list)),
                ('pdf_data', models.BinaryField()),
                ('file_size_bytes', models.IntegerField()),
                ('original_filename', models.CharField(max_length=255)),
                ('page_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('published', 'Published'), ('rejected', 'Rejected'), ('flagged', 'Flagged')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('view_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='users.section')),
                ('uploader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('inappropriate', 'Inappropriate Content'), ('copyright', 'Copyright Violation'), ('wrong_subject', 'Wrong Subject/Section'), ('duplicate', 'Duplicate Content'), ('other', 'Other')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('reviewed', 'Reviewed'), ('dismissed', 'Dismissed'), ('action_taken', 'Action Taken')], default='open', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='documents.document')),
                ('flagged_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raised_flags', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_flags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'document_flags',
            },
        ),
        migrations.CreateModel(
            name='DocumentViewLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('watermark_text', models.CharField(max_length=500)),
                ('viewed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_logs', to='documents.document')),
                ('viewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'document_view_logs',
                'indexes': [models.Index(fields=['document', '-viewed_at'], name='document_vi_documen_ce5637_idx'), models.Index(fields=['viewer', '-viewed_at'], name='document_vi_viewer__3c8a97_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['section', 'status'], name='documents_section_56845b_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['uploader', '-created_at'], name='documents_uploade_ea873b_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['-created_at'], name='documents_created_291bb4_idx'),
        ),
    ]
